### ISSUE TITLE
error while try to installing with pip install -r requirements.txt in ubuntu 20.04

### ISSUE THREAD

**Issue by matheuszig** [sarat9/ai-girlfriend#1]
Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      running egg_info
      error: PyObjC requires macOS to build
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by N1shank** [comment]
PyObjC is a bridge between Python and Objective-C. It allows Python scripts to use and extend existing Objective-C class libraries; most importantly the Cocoa libraries by Apple.

You can ignore this package and remove it from the requirements.txt without leaving behind a empty line in the file. 
Make sure you put your keys in environment variables.
