### ISSUE TITLE
Error running AI Girlfriend.exe

### ISSUE THREAD

**Issue by POOHPAH** [sarat9/ai-girlfriend#2]
When I execute AI Girlfriend.exe on Win 10 it doesn't do anything.  The size of the exe is 130,512 bytes (131,072 bytes on disk).  Running Process Explorer, AI Girlfriend.exe never shows up.

**Comment by sarat9** [comment]
The repository does not include an executable file. It is a Python-based repository, and you'll need to install the required dependencies and run the ai-gf.py script manually.

If you are bundling this as a separate executable file, ensure that it follows the same process
